#!/bin/sh


uci set network.lan.dns="114.114.114.114"
#uci set network.lan.delegate="0"
#uci set network.lan.ipaddr='192.168.77.1'
#uci set network.lan.proto='static'
#uci set network.lan.type='bridge'
#uci set network.lan.ifname='eth0'
#uci set network.wan.ifname='eth1'
uci set network.wan.peerdns="0"
uci set network.wan.dns="114.114.114.114"
#uci set network.wan6.peerdns="0"
#uci set network.wan6.dns="::1 2001:4860:4860::8888"
uci commit network

uci set firewall.@defaults[0].flow_offloading=1
uci set firewall.@defaults[0].flow_offloading_hw=1
uci commit firewall

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

exit 0
